// Deterministic KagGraph -> Mermaid flowchart serializer.
//
// UNLIKE mermaidGuard.ts, this file has no trust problem to solve: the Mermaid
// source it produces is generated by OUR code from OUR graph, never from model or
// user input. It exists purely to make the KAG routing graph (today only
// inspectable as JSON or via Neo4j Browser) readable in a Markdown preview or the
// /api/kag/graph.mmd debug endpoint.
//
// It still runs through guardMermaid() in scripts/test_mermaid.ts — not because
// this output needs guarding in production, but because that is the cheapest
// possible regression test for the guard itself: if a real assembled graph ever
// produces something the guard would refuse, that is a bug in this serializer.

import type { KagGraph, KagNode, KagNodeType, KagRelType } from './types';
import { escapeLabelAngles } from '../services/mermaidGuard';

export interface MermaidGraphOptions {
  /** Keep only nodes of these types (plus any Domain nodes needed for grouping). */
  nodeTypes?: KagNodeType[];
  /** Keep only edges of these types. */
  relTypes?: KagRelType[];
  /** Restrict to the neighborhood of one node id, breadth-first, within maxNodes. */
  rootId?: string;
  /** Mermaid layout degrades badly past ~100 nodes; default keeps it readable. */
  maxNodes?: number;
}

const DEFAULT_MAX_NODES = 60;

// Node shape by KagNodeType — cosmetic only, keeps the debug view scannable at a
// glance. Domain nodes don't need their own shape: they become `subgraph` blocks,
// never rendered as a node themselves.
const SHAPE: Record<Exclude<KagNodeType, 'Domain'>, [string, string]> = {
  Report: ['[', ']'],
  Table: ['[(', ')]'],
  Column: ['[/', '/]'],
  Metric: ['{{', '}}'],
  Dimension: ['[/', '\\]'],
  Entity: ['([', '])'],
  Term: ['>', ']'],
  Component: ['[[', ']]'],
};

/**
 * KagNode ids are `Type:slug`, and neither half is safe to emit verbatim.
 *
 * ':' is the obvious one — Mermaid can't parse it in an id. The one that actually
 * broke a real graph is '-': slugs contain hyphens, and the builder joins some ids
 * with a DOUBLE hyphen (`Report:sales--monthly-revenue-take-rate`). Mermaid reads
 * '--' as its link operator, so that line parsed as an EDGE and the whole diagram
 * died with "Expecting 'LINK'... got 'STR'" — the entire file, not one node.
 *
 * So the rule is an allowlist, not a blocklist: anything outside [A-Za-z0-9_]
 * becomes '_'. Collisions are impossible rather than merely unlikely, because
 * slugify() (types.ts) emits only [a-z0-9-] — no '_' ever originates in a slug, so
 * two distinct ids cannot map onto the same output.
 */
function mermaidId(id: string): string {
  return id.replace(/[^A-Za-z0-9_]/g, '_');
}

/** Quotes and newlines are the only characters Mermaid node/edge labels choke on. */
function escapeLabel(text: string): string {
  return text.replace(/"/g, '#quot;').replace(/\s*\n\s*/g, ' ').trim();
}

function renderNode(n: KagNode, indent: string): string {
  const [open, close] = SHAPE[n.type as Exclude<KagNodeType, 'Domain'>];
  return `${indent}${mermaidId(n.id)}${open}"${escapeLabel(n.label)}"${close}`;
}

/**
 * @param g Typically the return of `assembleGraph()` (backend/src/kag/kagBuilder.ts) —
 *   `AssembledGraph extends KagGraph`, so it can be passed here directly.
 */
export function graphToMermaid(g: KagGraph, opts: MermaidGraphOptions = {}): string {
  const maxNodes = opts.maxNodes ?? DEFAULT_MAX_NODES;

  let nodes = g.nodes;
  let edges = g.edges;

  // ── Explicit filters ───────────────────────────────────────────────────────
  // These are what the caller ASKED to see, so they are never reported as
  // truncation. Only the maxNodes budget below is an involuntary drop.
  if (opts.relTypes?.length) {
    const allowed = new Set(opts.relTypes);
    edges = edges.filter((e) => allowed.has(e.type));
  }

  if (opts.nodeTypes?.length) {
    const allowed = new Set<string>([...opts.nodeTypes, 'Domain']);
    nodes = nodes.filter((n) => allowed.has(n.type));
    const keep = new Set(nodes.map((n) => n.id));
    edges = edges.filter((e) => keep.has(e.from) && keep.has(e.to));
  }

  // ── rootId: narrow to the component reachable from one node ────────────────
  // The walk is deliberately UNBOUNDED here and capped further down with everything
  // else. Capping inside the walk would hide budget drops from the truncation note,
  // which is the one thing this serializer must never do.
  let bfsOrder: string[] | null = null;
  if (opts.rootId) {
    const present = new Set(nodes.map((n) => n.id));
    // Fail closed with a comment rather than a throw: this is a debug view, and a
    // typo'd id in a URL should produce a readable diagram saying so.
    if (!present.has(opts.rootId)) {
      return `%% root node not found in graph: ${opts.rootId}\nflowchart TD`;
    }

    // Undirected adjacency — a Column is just as much "near" its Table as the
    // reverse, and KAG edge direction is a modelling choice, not a reading order.
    const adjacency = new Map<string, string[]>();
    const link = (a: string, b: string) => {
      const list = adjacency.get(a);
      if (list) list.push(b);
      else adjacency.set(a, [b]);
    };
    for (const e of edges) {
      if (!present.has(e.from) || !present.has(e.to)) continue;
      link(e.from, e.to);
      link(e.to, e.from);
    }

    const seen = new Set<string>([opts.rootId]);
    bfsOrder = [opts.rootId];
    for (let i = 0; i < bfsOrder.length; i++) {
      for (const next of adjacency.get(bfsOrder[i]) ?? []) {
        if (seen.has(next)) continue;
        seen.add(next);
        bfsOrder.push(next);
      }
    }

    nodes = nodes.filter((n) => seen.has(n.id));
    edges = edges.filter((e) => seen.has(e.from) && seen.has(e.to));
  }

  // ── maxNodes budget ────────────────────────────────────────────────────────
  // Counts are captured BEFORE the cap so the note reports what the budget cost,
  // not what the filters above deliberately excluded.
  const eligibleNodes = nodes.length;
  const eligibleEdges = edges.length;

  if (nodes.length > maxNodes) {
    let kept: Set<string>;
    if (bfsOrder) {
      // Nearest-first. Degree ranking would be wrong here — it can evict the root
      // itself and leave a "neighborhood" that doesn't contain the node asked about.
      kept = new Set(bfsOrder.slice(0, maxNodes));
    } else {
      // Domain nodes are ALWAYS kept, ahead of the degree ranking below. A Domain's
      // own degree is just its direct IN_DOMAIN edge count, which can lose badly to
      // an individual well-connected Column/Table — that's how a real 4-domain graph
      // rendered only 2 domains at maxNodes:60. Domain count is tiny (single digits)
      // against any realistic budget, so reserving them outright costs nothing and
      // guarantees the grouping this whole view exists for is never silently partial.
      const alwaysKeep = nodes.filter((n) => n.type === 'Domain').map((n) => n.id);

      // Keep the highest-degree REMAINING nodes — they carry the most structure per node.
      const degree = new Map<string, number>();
      for (const e of edges) {
        degree.set(e.from, (degree.get(e.from) ?? 0) + 1);
        degree.set(e.to, (degree.get(e.to) ?? 0) + 1);
      }
      const budget = Math.max(0, maxNodes - alwaysKeep.length);
      const rest = [...nodes]
        .filter((n) => n.type !== 'Domain')
        .sort((a, b) => (degree.get(b.id) ?? 0) - (degree.get(a.id) ?? 0))
        .slice(0, budget)
        .map((n) => n.id);
      kept = new Set([...alwaysKeep, ...rest]);
    }
    nodes = nodes.filter((n) => kept.has(n.id));
    edges = edges.filter((e) => kept.has(e.from) && kept.has(e.to));
  }

  const truncatedNote =
    nodes.length < eligibleNodes || edges.length < eligibleEdges
      ? `%% truncated: ${nodes.length} of ${eligibleNodes} nodes, ` +
        `${edges.length} of ${eligibleEdges} edges shown\n`
      : '';

  // ── Domain grouping ────────────────────────────────────────────────────────
  // IN_DOMAIN points node -> Domain (see kagBuilder.ts).
  const domainOf = new Map<string, string>();
  for (const e of edges) {
    if (e.type === 'IN_DOMAIN') domainOf.set(e.from, e.to);
  }
  const domains = nodes.filter((n) => n.type === 'Domain');
  const domainIds = new Set(domains.map((n) => n.id));

  // Seeded with every surviving Domain so a domain whose members were all cut by
  // the budget still renders as an (empty) box. Dropping it instead would make a
  // node the truncation note counted as shown vanish with no trace.
  const byDomain = new Map<string, KagNode[]>(domains.map((d) => [d.id, []]));
  const ungrouped: KagNode[] = [];
  for (const n of nodes) {
    if (n.type === 'Domain') continue;
    const domainId = domainOf.get(n.id);
    const members = domainId ? byDomain.get(domainId) : undefined;
    if (members && domainIds.has(domainId!)) members.push(n);
    else ungrouped.push(n);
  }
  const domainLabel = new Map(domains.map((n) => [n.id, n.label]));

  const lines: string[] = [truncatedNote + 'flowchart TD'];

  for (const [domainId, members] of byDomain) {
    lines.push(`  subgraph ${mermaidId(domainId)}["${escapeLabel(domainLabel.get(domainId) ?? domainId)}"]`);
    for (const n of members) lines.push(renderNode(n, '    '));
    lines.push('  end');
  }
  for (const n of ungrouped) lines.push(renderNode(n, '  '));

  // Edges last: IN_DOMAIN edges are structural grouping, not something worth
  // drawing again as an arrow into the subgraph it already defines.
  for (const e of edges) {
    if (e.type === 'IN_DOMAIN') continue;
    lines.push(`  ${mermaidId(e.from)} -->|${e.type}| ${mermaidId(e.to)}`);
  }

  // The SAME normalization the model-authored M1 path applies, for the same reason.
  // Mermaid treats '>' as node-shape syntax and SILENTLY SWALLOWS a raw '>' inside a
  // quoted label — no error, just a different label. KAG metric names legitimately
  // contain one ("Take Rate > 4%?"), so without this the debug diagram would show a
  // confidently wrong metric name. escapeLabelAngles only rewrites double-quoted
  // spans, so the '>' in the Term flag shape (`id>"label"]`) and the `-->` arrows
  // are untouched, and it is idempotent, so an already-escaped label is left alone.
  return escapeLabelAngles(lines.join('\n'));
}
