// Shared types for the report → video pipeline.
// A report ({ meta, components }) is compiled into a VideoScript: an ordered
// list of scenes, each mirroring the user's 4-column model —
//   Scene (id/kind) · Visuals (visual) · On-screen text (onScreenText) · Narration.
// Remotion renders the script; ElevenLabs (Phase 2) fills narrationAudio.

export type SceneKind = 'cover' | 'kpis' | 'chart' | 'insight' | 'table' | 'outro';
export type ChartKind = 'bar' | 'line' | 'area' | 'pie';

export interface KpiDatum {
  label: string;
  value: string;   // display value, e.g. "$912K"
  trend?: string;
}

export interface ChartVisual {
  chartKind: ChartKind;
  labels: string[];
  series: { name: string; values: number[] }[];
}

export interface SceneVisual {
  kind: SceneKind;
  chart?: ChartVisual;         // kind === 'chart'
  kpis?: KpiDatum[];           // kind === 'kpis'
  table?: { columns: string[]; rows: string[][] };  // kind === 'table'
  accent?: string;             // hex, no '#'
  backgroundVideo?: string;    // URL to looping B-roll (hero scenes; added server-side)
}

export interface OnScreenText {
  kicker?: string;
  heading?: string;
  sub?: string;
  bullets?: string[];
}

export interface VideoScene {
  id: string;
  visual: SceneVisual;
  onScreenText: OnScreenText;
  narration: string;
  durationInFrames: number;
  narrationAudio?: string;     // Phase 2: object URL / data URL of TTS clip
}

export interface VideoScript {
  title: string;
  fps: number;
  width: number;
  height: number;
  scenes: VideoScene[];
}

// ── "What's new" release explainer ───────────────────────────────────────────
// A tiny, self-contained payload (generated by Claude from a change description)
// that the ReleaseNoteVideo composition renders into a 15–30s explainer.
export interface ReleaseNote {
  version: string;   // e.g. "2026.07.08" or a git tag
  title: string;     // one-line headline
  script: string;    // 2–4 sentence plain-language summary
  bullets: string[]; // short feature highlights
  // Optional narration, added at render time (the offline render embeds it as a
  // data URL). When present the video plays it and lasts at least as long as it.
  audioUrl?: string;
  audioDurationMs?: number;
}

// ── "What's new" release TOUR ────────────────────────────────────────────────
// A timeline-synced walkthrough: narration is split into beats (spoken phrases
// with timings from ElevenLabs word timestamps), and each beat shows a real,
// header-visible app footage shot with its words captioned — so the picture and
// caption always match what's being said in that window.
export interface TourBeat {
  text: string;               // the spoken phrase (caption)
  startFrame: number;         // relative to the feature segment start
  durationInFrames: number;
  footageUrl?: string;        // full-frame screen recording for this beat
}
export interface TourSegment {
  kicker?: string;
  heading: string;
  audioUrl?: string;          // per-feature narration (played across its beats)
  durationInFrames: number;
  beats: TourBeat[];
  // When set, the feature is illustrated by a native recreated-UI scene
  // ('chat-kpi' | 'export-docs' | 'export-video') instead of screen-capture
  // footage. Captions still sync to the beats.
  mock?: string;
}
export interface TourHero {
  kicker?: string;
  heading: string;
  sub?: string;
  audioUrl?: string;
  durationInFrames: number;
}
export interface ReleaseTour {
  title: string;
  version: string;
  fps: number;
  width: number;
  height: number;
  cover: TourHero;
  features: TourSegment[];
  outro: TourHero;
}

export const VIDEO_FPS = 30;
export const VIDEO_W = 1920;
export const VIDEO_H = 1080;
